-- MySQL Script generated by MySQL Workbench
-- Wed Jan 25 13:39:18 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema es_court
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema es_court
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `es_court` DEFAULT CHARACTER SET utf8 ;
USE `es_court` ;

-- -----------------------------------------------------
-- Table `es_court`.`menber_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `es_court`.`menber_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `es_court`.`masters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `es_court`.`masters` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(256) NULL,
  `password` VARCHAR(256) NULL,
  `member_type_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk__masters__member_type_id_idx` (`member_type_id` ASC),
  CONSTRAINT `fk__masters__member_type_id`
    FOREIGN KEY (`member_type_id`)
    REFERENCES `es_court`.`menber_types` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `es_court`.`jobs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `es_court`.`jobs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `es_court`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `es_court`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` DATETIME NULL,
  `email` VARCHAR(256) NULL,
  `password` VARCHAR(256) NULL,
  `postcode` VARCHAR(256) NULL,
  `address` MEDIUMTEXT NULL,
  `tel` VARCHAR(256) NULL,
  `family_name` VARCHAR(256) NULL,
  `first_name` VARCHAR(256) NULL,
  `birthday` DATETIME NULL,
  `member_type_id` INT NULL,
  `gender` INT NULL,
  `job_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk__users__member_type_id_idx` (`member_type_id` ASC),
  INDEX `fk__users__job_id_idx` (`job_id` ASC),
  CONSTRAINT `fk__users__member_type_id`
    FOREIGN KEY (`member_type_id`)
    REFERENCES `es_court`.`menber_types` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk__users__job_id`
    FOREIGN KEY (`job_id`)
    REFERENCES `es_court`.`jobs` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `es_court`.`administrators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `es_court`.`administrators` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` DATETIME NULL,
  `crawler_path` VARCHAR(256) NULL,
  `reserver_path` VARCHAR(256) NULL,
  `name` VARCHAR(256) NULL,
  `postcode` VARCHAR(256) NULL,
  `address` MEDIUMTEXT NULL,
  `email` VARCHAR(256) NULL,
  `password` VARCHAR(256) NULL,
  `tel` VARCHAR(256) NULL,
  `member_type_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk__administrators__member_type_id_idx` (`member_type_id` ASC),
  CONSTRAINT `fk__administrators__member_type_id`
    FOREIGN KEY (`member_type_id`)
    REFERENCES `es_court`.`menber_types` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `es_court`.`facilities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `es_court`.`facilities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` DATETIME NULL,
  `name` VARCHAR(256) NULL,
  `postcode` VARCHAR(256) NULL,
  `address` MEDIUMTEXT NULL,
  `crawler_path` VARCHAR(256) NULL,
  `reserver_path` VARCHAR(256) NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `description` MEDIUMTEXT NULL,
  `administrator_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk__ facilities__administrator_id_idx` (`administrator_id` ASC),
  CONSTRAINT `fk__ facilities__administrator_id`
    FOREIGN KEY (`administrator_id`)
    REFERENCES `es_court`.`administrators` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `es_court`.`court_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `es_court`.`court_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `es_court`.`frames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `es_court`.`frames` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` DATETIME NULL,
  `date` DATETIME NULL,
  `reserved` INT NULL,
  `name` VARCHAR(256) NULL,
  `court_type_id` INT NULL,
  `facility_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk__frames__court_type_id_idx` (`court_type_id` ASC),
  INDEX `fk__frames__facility_id_idx` (`facility_id` ASC),
  CONSTRAINT `fk__frames__court_type_id`
    FOREIGN KEY (`court_type_id`)
    REFERENCES `es_court`.`court_types` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk__frames__facility_id`
    FOREIGN KEY (`facility_id`)
    REFERENCES `es_court`.`facilities` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `es_court`.`reserves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `es_court`.`reserves` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` DATETIME NULL,
  `user_id` INT NULL,
  `frame_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk__reservers__user_id_idx` (`user_id` ASC),
  INDEX `fk__reservers__frame_id_idx` (`frame_id` ASC),
  CONSTRAINT `fk__reservers__user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `es_court`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk__reservers__frame_id`
    FOREIGN KEY (`frame_id`)
    REFERENCES `es_court`.`frames` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `es_court`.`notifies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `es_court`.`notifies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(256) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `es_court`.`waits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `es_court`.`waits` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` DATETIME NULL,
  `user_id` INT NULL,
  `notify_id` INT NULL,
  `facility_id` INT NULL,
  `central_latitude` DOUBLE NULL,
  `central_longitude` DOUBLE NULL,
  `distance` INT NULL,
  `start` DATETIME NULL,
  `end` VARCHAR(256) NULL,
  `size` INT NULL,
  `succession` INT NULL,
  `must` INT NULL,
  `max_price` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk__waits__user_id_idx` (`user_id` ASC),
  INDEX `fk__waits__notify_id_idx` (`notify_id` ASC),
  INDEX `fk__waits__facility_id_idx` (`facility_id` ASC),
  CONSTRAINT `fk__waits__user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `es_court`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk__waits__notify_id`
    FOREIGN KEY (`notify_id`)
    REFERENCES `es_court`.`notifies` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk__waits__facility_id`
    FOREIGN KEY (`facility_id`)
    REFERENCES `es_court`.`facilities` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `es_court`.`facility_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `es_court`.`facility_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` DATETIME NULL,
  `facility_id` INT NULL,
  `image_url` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk__ facility_images__facility_id_idx` (`facility_id` ASC),
  CONSTRAINT `fk__ facility_images__facility_id`
    FOREIGN KEY (`facility_id`)
    REFERENCES `es_court`.`facilities` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `es_court`.`reserveables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `es_court`.`reserveables` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `wait_id` INT NULL,
  `confirmed` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk__ reserveable__wait_id_idx` (`wait_id` ASC),
  CONSTRAINT `fk__ reserveable__wait_id`
    FOREIGN KEY (`wait_id`)
    REFERENCES `es_court`.`waits` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `es_court`.`queues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `es_court`.`queues` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` DATETIME NULL,
  `frame_id` INT NULL,
  `reservable_id` INT NULL,
  `reservable` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk__queues__frame_id_idx` (`frame_id` ASC),
  INDEX `fk__queues__reservable__id_idx` (`reservable_id` ASC),
  CONSTRAINT `fk__queues__frame_id`
    FOREIGN KEY (`frame_id`)
    REFERENCES `es_court`.`frames` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk__queues__reservable__id`
    FOREIGN KEY (`reservable_id`)
    REFERENCES `es_court`.`reserveables` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `es_court`.`passwords`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `es_court`.`passwords` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created` DATETIME NULL,
  `modified` DATETIME NULL,
  `deleted` DATETIME NULL,
  `user_id` INT NULL,
  `administrator_id` INT NULL,
  `username` VARCHAR(256) NULL,
  `password` VARCHAR(256) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk__passwords__user_id_idx` (`user_id` ASC),
  INDEX `fk__passwords__administrator_id_idx` (`administrator_id` ASC),
  CONSTRAINT `fk__passwords__user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `es_court`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk__passwords__administrator_id`
    FOREIGN KEY (`administrator_id`)
    REFERENCES `es_court`.`administrators` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;





